### ISSUE TITLE
Praying using words that are not in the Quran will render your prayer as invalid

### ISSUE THREAD

**Issue by kar-mei** [Flinesoft/Prayer#7]
Hello,

I would like to thank the developers of this application for taking the time and effort to create it ❤. But it seems that the developer is not aware that praying with the translation of the Quran is not allowed and will void your prayer. You must read at least the [Al-Fatiha](https://fr.wikipedia.org/wiki/Al-Fatiha) [Surah](https://en.wikipedia.org/wiki/Surah) in Arabic is order for your prayer to be valid (even if you don't understand it).

Thanks for your time.

**Comment by Jeehut** [comment]
Hello @kar-mei, thank you for using the app. I'm sorry to get back to you so late, I did not see your message in my inboxes, now that I'm planning to update the app I'm seeing it.

Now let me get to your point: You're stating that some part (you mentioned the surah ["The Opening"](https://github.com/Flinesoft/Prayer/blob/main/App/Resources/Recitations/en.lproj/001_The-Opening.txt) as a minimum) needs to be recited in Arabic in order for the prayer to be valid. Do you have any **source** for this? Is your source **based on the Quran**? My approach is to keep my decisions as close as possible to the Quran and I couldn't see any statements about the language in it, but I'm willing to learn.

What I explicitly don't care about is opinions simply based on "how it was done by the prophet or the first Muslims". For me the question to answer is rather: "How would the prophet do it if he lived _today_ and grew up like me in the _same country, culture and language_ I grew up in?"

Looking forward to your inputs! :)

**Comment by Jeehut** [comment]
@kar-mei I'm closing this as this is neither a bug report, nor a feature request. Instead, it's a discussion topic and for discussions, we have our Community forum. For this topic, there's even already an FAQ entry which you could reply to if you wanted to discuss this further:
https://community.flinesoft.com/t/do-prayers-not-have-to-be-spoken-in-arabic-the-original-language-of-the-koran/22
